.github/workflows/benchmark-ci.yml
azure-pipelines.yml
benchmarks/asv_bench/asv.conf.json

Fix upstream url in benchmark-ci.yml.
Fixes #xxxx

CI: Fix benchmark CI

---

CODEOWNERS

Chore: Remove code owners

---

merge_helper.sh

Add a helper script to cherry-pick commits from mars-project/mars.

Chore: Add merge helper

---

mars/services/task/supervisor/processor.py

Fix execution hang on optimization error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Refine github issue template.
Fixes #xxxx

chore: Refine github issue template

---

.github/workflows/platform-ci.yml
mars/core/operand/shuffle.py
mars/deploy/oscar/session.py
mars/learn/decomposition/_pca.py
mars/learn/ensemble/_bagging.py
mars/learn/ensemble/tests/test_bagging.py
mars/learn/preprocessing/tests/test_label.py
mars/learn/utils/_encode.py
mars/learn/utils/core.py
mars/learn/wrappers.py
mars/lib/filesystem/s3.py
mars/lib/sparse/array.py
mars/metrics/api.py
mars/oscar/backends/ray/communication.py
mars/remote/core.py
mars/services/subtask/core.py
mars/services/task/analyzer/analyzer.py
mars/services/task/execution/mars/executor.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py
mars/services/task/execution/utils.py
mars/tensor/statistics/bincount.py
mars/utils.py
setup.cfg

chore: Merge community master

---

mars/deploy/utils.py
mars/oscar/backends/pool.py
mars/services/cluster/file_logger.py

Remove absolute imports.
Fixes #xxxx

enh: Remove all absolute import

---

.github/workflows/core-gpu-ci.yml
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/tseries/tests/test_tseries_execution.py
mars/dataframe/tseries/to_datetime.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/optimization/logical/tileable/tests/test_arithmetic_query.py
mars/services/task/analyzer/fusion.py
mars/tests/core.py
mars/tests/test_utils.py
mars/utils.py

enh: Support `read_parquet` for GPU

---

mars/dataframe/__init__.py

Exposes some classes in Dataframe module to follow the pandas behaviors.
Fixes #xxxx

Exposes some classes in Dataframe module

---

MANIFEST.in
mars/dataframe/datastore/tests/test_datastore_execution.py
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/file-logging.conf
mars/deploy/oscar/local.py
mars/deploy/oscar/pool.py
mars/deploy/oscar/tests/test_cmdline.py
mars/deploy/oscar/tests/test_pool.py
mars/services/cluster/api/core.py
mars/services/cluster/api/oscar.py
mars/services/cluster/api/web.py
mars/services/cluster/file_logger.py
mars/services/cluster/tests/test_api.py
mars/services/cluster/tests/test_file_logger.py
mars/services/web/ui/package-lock.json
mars/services/web/ui/package.json
mars/services/web/ui/src/node_info/NodeLogTab.js

1. web log streaming download way
2. segmented transfer when downloading logs
3. fix #47

Improve log download on web

---

.github/workflows/os-compat-ci.yml

Pin pyarrow<10.0 to fix windows CI
Fixes #xxxx

Fix windows CI

---

mars/services/task/analyzer/analyzer.py

Revert concat optimization.
Fixes #xxxx

Revert part of concat optimization

---

.github/workflows/benchmark-ci.yml
azure-pipelines.yml
benchmarks/asv_bench/asv.conf.json
benchmarks/asv_bench/benchmarks/storage.py
benchmarks/tpch/run_queries.py
mars/_utils.pyx
mars/core/context.py
mars/core/entity/tileables.py
mars/core/operand/base.py
mars/dataframe/utils.py
mars/deploy/oscar/pool.py
mars/remote/tests/test_remote_function.py
mars/serialization/serializables/field.py
mars/services/context.py
mars/services/task/analyzer/analyzer.py
mars/services/task/analyzer/assigner.py

This PR added support for running TPC-H queries on GPU.
Fixes #xxxx

enh: Support running TPC-H queries on GPU

---

mars/services/web/ui/package-lock.json
mars/services/web/ui/package.json
mars/services/web/ui/src/Utils.js
mars/services/web/ui/src/task_info/TaskListPage.js
mars/services/web/ui/webpack.config.js
setup.py

1. Simplify build web
2. add task duration time on web

Enh: add task duration on web

---

azure-pipelines.yml
mars/oscar/backends/communication/utils.py

enh: Refactor `read_buffers` & `write_buffers` for GPU

---

mars/lib/nvutils.py
mars/lib/tests/test_nvutils.py

enh: Enrich nvutils

---

mars/dataframe/missing/checkna.py
mars/dataframe/missing/tests/test_missing.py

let `dataframe.isna` handle scalers.
Resolves #54

Fix: dataframe.isna on scaler args

---

mars/core/entity/objects.py
mars/core/entity/tileables.py
mars/remote/run_script.py

Make Object a subclass of Tileable

---

mars/deploy/oscar/local.py
mars/services/cluster/api/web.py

Bugfix: error on stack page and logging in CI

---

.github/workflows/core-ci.yml
mars/deploy/oscar/base_config.yml
mars/deploy/oscar/local.py
mars/deploy/oscar/pool.py
mars/deploy/oscar/supervisor.py
mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/worker.py
mars/optimization/logical/tileable/column_pruning/column_pruning_rule.py
mars/oscar/backend.py
mars/oscar/backends/communication/__init__.py
mars/oscar/backends/communication/base.py
mars/oscar/backends/communication/socket.py
mars/oscar/backends/communication/tests/test_comm.py
mars/oscar/backends/communication/ucx.py
mars/oscar/backends/config.py
mars/oscar/backends/mars/backend.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/pool.py
mars/oscar/backends/ray/pool.py
mars/oscar/backends/router.py
mars/oscar/backends/test/pool.py
mars/serialization/aio.py
mars/services/task/execution/utils.py
mars/tests/core.py
mars/tests/test_cluster.py
mars/utils.py

feat: Support ucx channel for oscar

---

.github/workflows/platform-ci.yml

Pin version: "vineyard<0.11.0".
Fixes #xxxx

fix: ci: fixed vineyard version

---

mars/conftest.py
mars/tests/test_cluster.py

test: Check process status instead of sleep in test_cluster

---

mars/tensor/lib/index_tricks.py

Enh: implement MGridClass and OGridClass for better doc

---

.github/workflows/platform-ci.yml
azure-pipelines.yml

- Fix scikit-learn version.
- Fix ubuntu version for k8s and yarn.
Fixes #xxxx

Fix some CI issues

---

mars/deploy/oscar/cmdline.py

BUG: remove absolute import

---

mars/dataframe/initializer.py
mars/dataframe/reduction/tests/test_reduction_execution.py
mars/dataframe/reduction/unique.py

Fixes https://github.com/xprobe-inc/mars/issues/101, and enhance series dtype interpretion.
Fixes #101

BUG: Fix md.unique

---

mars/deploy/oscar/cmdline.py
mars/deploy/oscar/pool.py
mars/deploy/oscar/tests/test_pool.py

BUG: Cannot config debug logger when using default logging file

---

mars/dataframe/plotting/__init__.py
mars/dataframe/plotting/tests/test_plot.py

Enh: support groupby plot

---

mars/dataframe/window/aggregation.py
mars/dataframe/window/ewm/tests/test_ewm.py
mars/dataframe/window/ewm/tests/test_ewm_execution.py
mars/dataframe/window/expanding/tests/test_expanding.py

Fix dataframe.ewm 

---

mars/core/context.py
mars/core/tests/test_context.py
mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py
mars/services/subtask/worker/processor.py
mars/services/task/execution/mars/executor.py

ENH: Clear default context after execution

---

mars/dataframe/indexing/sample.py
mars/dataframe/indexing/tests/test_indexing_execution.py

BUG: Fix dataframe.sample()

---

mars/deploy/oscar/supervisor.py

BUG: fix supervisor start method

---

docs/requirements-doc.txt
mars/dataframe/datasource/date_range.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/tensor/stats/tests/test_stats_execution.py

Fix `date_range` and pin sphinx<6.0.0, related issue in sphinx: https://github.com/sphinx-doc/sphinx/issues/11062
Fixes #xxxx

BUG: Fix `date_range` and pin sphinx<6.0.0

---

.github/workflows/platform-ci.yml
ci/install-hadoop.sh
mars/dataframe/plotting/core.py
mars/resource.py
mars/tests/test_resource.py

Support cgroup V2 to detect resources.
Fixes #xxxx

ENH: Support cgroup V2

---

mars/services/web/handlers.py
mars/services/web/indexhandler.py
mars/services/web/supervisor.py

ENH: Register web handler when starting tornado

---

mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction_execution.py

BUG: DataFrame.agg with built-in functions

---

mars/oscar/backends/mars/pool.py
mars/oscar/backends/pool.py
mars/services/cluster/uploader.py

Silence exception log when python process exit.
Fixes #112

ENH: Silence exception log when python process exit

---

mars/deploy/oscar/local.py
mars/deploy/oscar/pool.py

Make local cluster logging configurable.
Fixes #xxxx

Make local cluster logging configurable

---

mars/dataframe/merge/merge.py
mars/dataframe/merge/tests/test_merge.py
mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py

BUG: handle missing merge key

---

mars/metrics/api.py
mars/serialization/ray.py
mars/services/task/execution/ray/executor.py

Silence logs about ray when importing mars.
Fixes #xxxx

ENH: Silence logs about ray when importing mars

---

mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py

Fix `read_csv` with specific names and header.
Fixes #127

BUG: Fix `read_csv` with specific names and header

---

mars/core/graph/core.pyx
mars/dataframe/groupby/aggregation.py
mars/optimization/logical/tileable/column_pruning/column_pruning_rule.py
mars/optimization/logical/tileable/column_pruning/input_column_selector.py
mars/optimization/logical/tileable/column_pruning/self_column_selector.py
mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py
mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py
mars/optimization/logical/tileable/column_pruning/tests/test_self_column_selector.py
mars/optimization/logical/tileable/column_pruning/utils.py

BUG: needed cols being pruned
